network_class: CHNN
body_class: Gyroscope
dataset_class: RigidBodyDataset
batch_size: 128
body_args: null
n_hidden: 256
n_layers: 8
n_train_systems: 1000
n_train: 800
n_val: 100
n_test: 100
chunk_len: 5
regen: false
lr: 0.003
no_lr_sched: false
n_epochs: 2000
weight_decay: 0.0001
tol: 1.0e-07
seed: 0
optimizer_class: AdamW
_instantiator: lightning.pytorch.cli.instantiate_module
